# fly.toml app configuration file generated for poker-hand-comparator on 2024-09-08T03:20:28-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'poker-hand-comparator'
primary_region = 'bog'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[build]
builder = "paketobuildpacks/builder:base"

[[services]]
internal_port = 8080
protocol = "tcp"

[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[env]
BPL_JVM_HEAD_ROOM = "0"
BPL_JVM_THREAD_COUNT = "50"
BPL_JVM_LOADED_CLASS_COUNT = "15000"
BPL_JVM_HEAP_SIZE = "256M"
